// export const timeZones = [
//   "Europe/Andorra",
//   "Asia/Dubai",
//   "Asia/Kabul",
//   "Europe/Tirane",
//   "Asia/Yerevan",
//   "Antarctica/Casey",
//   "Antarctica/Davis",
//   "Antarctica/DumontDUrville", // https://bugs.chromium.org/p/chromium/issues/detail?id=928068
//   "Antarctica/Mawson",
//   "Antarctica/Palmer",
//   "Antarctica/Rothera",
//   "Antarctica/Syowa",
//   "Antarctica/Troll",
//   "Antarctica/Vostok",
//   "America/Argentina/Buenos_Aires",
//   "America/Argentina/Cordoba",
//   "America/Argentina/Salta",
//   "America/Argentina/Jujuy",
//   "America/Argentina/Tucuman",
//   "America/Argentina/Catamarca",
//   "America/Argentina/La_Rioja",
//   "America/Argentina/San_Juan",
//   "America/Argentina/Mendoza",
//   "America/Argentina/San_Luis",
//   "America/Argentina/Rio_Gallegos",
//   "America/Argentina/Ushuaia",
//   "Pacific/Pago_Pago",
//   "Europe/Vienna",
//   "Australia/Lord_Howe",
//   "Antarctica/Macquarie",
//   "Australia/Hobart",
//   "Australia/Currie",
//   "Australia/Melbourne",
//   "Australia/Sydney",
//   "Australia/Broken_Hill",
//   "Australia/Brisbane",
//   "Australia/Lindeman",
//   "Australia/Adelaide",
//   "Australia/Darwin",
//   "Australia/Perth",
//   "Australia/Eucla",
//   "Asia/Baku",
//   "America/Barbados",
//   "Asia/Dhaka",
//   "Europe/Brussels",
//   "Europe/Sofia",
//   "Atlantic/Bermuda",
//   "Asia/Brunei",
//   "America/La_Paz",
//   "America/Noronha",
//   "America/Belem",
//   "America/Fortaleza",
//   "America/Recife",
//   "America/Araguaina",
//   "America/Maceio",
//   "America/Bahia",
//   "America/Sao_Paulo",
//   "America/Campo_Grande",
//   "America/Cuiaba",
//   "America/Santarem",
//   "America/Porto_Velho",
//   "America/Boa_Vista",
//   "America/Manaus",
//   "America/Eirunepe",
//   "America/Rio_Branco",
//   "America/Nassau",
//   "Asia/Thimphu",
//   "Europe/Minsk",
//   "America/Belize",
//   "America/St_Johns",
//   "America/Halifax",
//   "America/Glace_Bay",
//   "America/Moncton",
//   "America/Goose_Bay",
//   "America/Blanc-Sablon",
//   "America/Toronto",
//   "America/Nipigon",
//   "America/Thunder_Bay",
//   "America/Iqaluit",
//   "America/Pangnirtung",
//   "America/Atikokan",
//   "America/Winnipeg",
//   "America/Rainy_River",
//   "America/Resolute",
//   "America/Rankin_Inlet",
//   "America/Regina",
//   "America/Swift_Current",
//   "America/Edmonton",
//   "America/Cambridge_Bay",
//   "America/Yellowknife",
//   "America/Inuvik",
//   "America/Creston",
//   "America/Dawson_Creek",
//   "America/Fort_Nelson",
//   "America/Vancouver",
//   "America/Whitehorse",
//   "America/Dawson",
//   "Indian/Cocos",
//   "Europe/Zurich",
//   "Africa/Abidjan",
//   "Pacific/Rarotonga",
//   "America/Santiago",
//   "America/Punta_Arenas",
//   "Pacific/Easter",
//   "Asia/Shanghai",
//   "Asia/Urumqi",
//   "America/Bogota",
//   "America/Costa_Rica",
//   "America/Havana",
//   "Atlantic/Cape_Verde",
//   "America/Curacao",
//   "Indian/Christmas",
//   "Asia/Nicosia",
//   "Asia/Famagusta",
//   "Europe/Prague",
//   "Europe/Berlin",
//   "Europe/Copenhagen",
//   "America/Santo_Domingo",
//   "Africa/Algiers",
//   "America/Guayaquil",
//   "Pacific/Galapagos",
//   "Europe/Tallinn",
//   "Africa/Cairo",
//   "Africa/El_Aaiun",
//   "Europe/Madrid",
//   "Africa/Ceuta",
//   "Atlantic/Canary",
//   "Europe/Helsinki",
//   "Pacific/Fiji",
//   "Atlantic/Stanley",
//   "Pacific/Chuuk",
//   "Pacific/Pohnpei",
//   "Pacific/Kosrae",
//   "Atlantic/Faroe",
//   "Europe/Paris",
//   "Europe/London",
//   "Asia/Tbilisi",
//   "America/Cayenne",
//   "Africa/Accra",
//   "Europe/Gibraltar",
//   "America/Godthab",
//   "America/Danmarkshavn",
//   "America/Scoresbysund",
//   "America/Thule",
//   "Europe/Athens",
//   "Atlantic/South_Georgia",
//   "America/Guatemala",
//   "Pacific/Guam",
//   "Africa/Bissau",
//   "America/Guyana",
//   "Asia/Hong_Kong",
//   "America/Tegucigalpa",
//   "America/Port-au-Prince",
//   "Europe/Budapest",
//   "Asia/Jakarta",
//   "Asia/Pontianak",
//   "Asia/Makassar",
//   "Asia/Jayapura",
//   "Europe/Dublin",
//   "Asia/Jerusalem",
//   "Asia/Kolkata",
//   "Indian/Chagos",
//   "Asia/Baghdad",
//   "Asia/Tehran",
//   "Atlantic/Reykjavik",
//   "Europe/Rome",
//   "America/Jamaica",
//   "Asia/Amman",
//   "Asia/Tokyo",
//   "Africa/Nairobi",
//   "Asia/Bishkek",
//   "Pacific/Tarawa",
//   "Pacific/Enderbury",
//   "Pacific/Kiritimati",
//   "Asia/Pyongyang",
//   "Asia/Seoul",
//   "Asia/Almaty",
//   "Asia/Qyzylorda",
//   "Asia/Qostanay", // https://bugs.chromium.org/p/chromium/issues/detail?id=928068
//   "Asia/Aqtobe",
//   "Asia/Aqtau",
//   "Asia/Atyrau",
//   "Asia/Oral",
//   "Asia/Beirut",
//   "Asia/Colombo",
//   "Africa/Monrovia",
//   "Europe/Vilnius",
//   "Europe/Luxembourg",
//   "Europe/Riga",
//   "Africa/Tripoli",
//   "Africa/Casablanca",
//   "Europe/Monaco",
//   "Europe/Chisinau",
//   "Pacific/Majuro",
//   "Pacific/Kwajalein",
//   "Asia/Yangon",
//   "Asia/Ulaanbaatar",
//   "Asia/Hovd",
//   "Asia/Choibalsan",
//   "Asia/Macau",
//   "America/Martinique",
//   "Europe/Malta",
//   "Indian/Mauritius",
//   "Indian/Maldives",
//   "America/Mexico_City",
//   "America/Cancun",
//   "America/Merida",
//   "America/Monterrey",
//   "America/Matamoros",
//   "America/Mazatlan",
//   "America/Chihuahua",
//   "America/Ojinaga",
//   "America/Hermosillo",
//   "America/Tijuana",
//   "America/Bahia_Banderas",
//   "Asia/Kuala_Lumpur",
//   "Asia/Kuching",
//   "Africa/Maputo",
//   "Africa/Windhoek",
//   "Pacific/Noumea",
//   "Pacific/Norfolk",
//   "Africa/Lagos",
//   "America/Managua",
//   "Europe/Amsterdam",
//   "Europe/Oslo",
//   "Asia/Kathmandu",
//   "Pacific/Nauru",
//   "Pacific/Niue",
//   "Pacific/Auckland",
//   "Pacific/Chatham",
//   "America/Panama",
//   "America/Lima",
//   "Pacific/Tahiti",
//   "Pacific/Marquesas",
//   "Pacific/Gambier",
//   "Pacific/Port_Moresby",
//   "Pacific/Bougainville",
//   "Asia/Manila",
//   "Asia/Karachi",
//   "Europe/Warsaw",
//   "America/Miquelon",
//   "Pacific/Pitcairn",
//   "America/Puerto_Rico",
//   "Asia/Gaza",
//   "Asia/Hebron",
//   "Europe/Lisbon",
//   "Atlantic/Madeira",
//   "Atlantic/Azores",
//   "Pacific/Palau",
//   "America/Asuncion",
//   "Asia/Qatar",
//   "Indian/Reunion",
//   "Europe/Bucharest",
//   "Europe/Belgrade",
//   "Europe/Kaliningrad",
//   "Europe/Moscow",
//   "Europe/Simferopol",
//   "Europe/Kirov",
//   "Europe/Astrakhan",
//   "Europe/Volgograd",
//   "Europe/Saratov",
//   "Europe/Ulyanovsk",
//   "Europe/Samara",
//   "Asia/Yekaterinburg",
//   "Asia/Omsk",
//   "Asia/Novosibirsk",
//   "Asia/Barnaul",
//   "Asia/Tomsk",
//   "Asia/Novokuznetsk",
//   "Asia/Krasnoyarsk",
//   "Asia/Irkutsk",
//   "Asia/Chita",
//   "Asia/Yakutsk",
//   "Asia/Khandyga",
//   "Asia/Vladivostok",
//   "Asia/Ust-Nera",
//   "Asia/Magadan",
//   "Asia/Sakhalin",
//   "Asia/Srednekolymsk",
//   "Asia/Kamchatka",
//   "Asia/Anadyr",
//   "Asia/Riyadh",
//   "Pacific/Guadalcanal",
//   "Indian/Mahe",
//   "Africa/Khartoum",
//   "Europe/Stockholm",
//   "Asia/Singapore",
//   "America/Paramaribo",
//   "Africa/Juba",
//   "Africa/Sao_Tome",
//   "America/El_Salvador",
//   "Asia/Damascus",
//   "America/Grand_Turk",
//   "Africa/Ndjamena",
//   "Indian/Kerguelen",
//   "Asia/Bangkok",
//   "Asia/Dushanbe",
//   "Pacific/Fakaofo",
//   "Asia/Dili",
//   "Asia/Ashgabat",
//   "Africa/Tunis",
//   "Pacific/Tongatapu",
//   "Europe/Istanbul",
//   "America/Port_of_Spain",
//   "Pacific/Funafuti",
//   "Asia/Taipei",
//   "Europe/Kiev",
//   "Europe/Uzhgorod",
//   "Europe/Zaporozhye",
//   "Pacific/Wake",
//   "America/New_York",
//   "America/Detroit",
//   "America/Kentucky/Louisville",
//   "America/Kentucky/Monticello",
//   "America/Indiana/Indianapolis",
//   "America/Indiana/Vincennes",
//   "America/Indiana/Winamac",
//   "America/Indiana/Marengo",
//   "America/Indiana/Petersburg",
//   "America/Indiana/Vevay",
//   "America/Chicago",
//   "America/Indiana/Tell_City",
//   "America/Indiana/Knox",
//   "America/Menominee",
//   "America/North_Dakota/Center",
//   "America/North_Dakota/New_Salem",
//   "America/North_Dakota/Beulah",
//   "America/Denver",
//   "America/Boise",
//   "America/Phoenix",
//   "America/Los_Angeles",
//   "America/Anchorage",
//   "America/Juneau",
//   "America/Sitka",
//   "America/Metlakatla",
//   "America/Yakutat",
//   "America/Nome",
//   "America/Adak",
//   "Pacific/Honolulu",
//   "America/Montevideo",
//   "Asia/Samarkand",
//   "Asia/Tashkent",
//   "America/Caracas",
//   "Asia/Ho_Chi_Minh",
//   "Pacific/Efate",
//   "Pacific/Wallis",
//   "Pacific/Apia",
//   "Africa/Johannesburg",
// ];

import _ from "lodash";

export const timeZones = [
  { ID: 1, timeZoneID: "Africa/Abidjan", displayName: "Greenwich Mean Time" },
  { ID: 2, timeZoneID: "Africa/Accra", displayName: "Greenwich Mean Time" },
  { ID: 3, timeZoneID: "Africa/Algiers", displayName: "Central European Time" },
  { ID: 4, timeZoneID: "Africa/Bissau", displayName: "Greenwich Mean Time" },
  { ID: 5, timeZoneID: "Africa/Cairo", displayName: "Eastern European Time" },
  {
    ID: 6,
    timeZoneID: "Africa/Casablanca",
    displayName: "Western European Time",
  },
  { ID: 7, timeZoneID: "Africa/Ceuta", displayName: "Central European Time" },
  {
    ID: 8,
    timeZoneID: "Africa/El_Aaiun",
    displayName: "Western European Time",
  },
  {
    ID: 9,
    timeZoneID: "Africa/Johannesburg",
    displayName: "South Africa Standard Time",
  },
  { ID: 10, timeZoneID: "Africa/Juba", displayName: "" },
  {
    ID: 11,
    timeZoneID: "Africa/Khartoum",
    displayName: "Eastern African Time",
  },
  { ID: 12, timeZoneID: "Africa/Lagos", displayName: "Western African Time" },
  { ID: 13, timeZoneID: "Africa/Maputo", displayName: "Central African Time" },
  { ID: 14, timeZoneID: "Africa/Monrovia", displayName: "Greenwich Mean Time" },
  { ID: 15, timeZoneID: "Africa/Nairobi", displayName: "Eastern African Time" },
  {
    ID: 16,
    timeZoneID: "Africa/Ndjamena",
    displayName: "Western African Time",
  },
  { ID: 17, timeZoneID: "Africa/Sao_Tome", displayName: "Greenwich Mean Time" },
  {
    ID: 18,
    timeZoneID: "Africa/Tripoli",
    displayName: "Eastern European Time",
  },
  { ID: 19, timeZoneID: "Africa/Tunis", displayName: "Central European Time" },
  {
    ID: 20,
    timeZoneID: "Africa/Windhoek",
    displayName: "Western African Time",
  },
  {
    ID: 21,
    timeZoneID: "America/Adak",
    displayName: "Hawaii-Aleutian Standard Time",
  },
  {
    ID: 22,
    timeZoneID: "America/Anchorage",
    displayName: "Alaska Standard Time",
  },
  { ID: 23, timeZoneID: "America/Araguaina", displayName: "Brazil Time" },
  { ID: 24, timeZoneID: "America/Argentina/Buenos_Aires", displayName: "" },
  { ID: 25, timeZoneID: "America/Argentina/Catamarca", displayName: "" },
  { ID: 26, timeZoneID: "America/Argentina/Cordoba", displayName: "" },
  { ID: 27, timeZoneID: "America/Argentina/Jujuy", displayName: "" },
  { ID: 28, timeZoneID: "America/Argentina/La_Rioja", displayName: "" },
  { ID: 29, timeZoneID: "America/Argentina/Mendoza", displayName: "" },
  { ID: 30, timeZoneID: "America/Argentina/Rio_Gallegos", displayName: "" },
  { ID: 31, timeZoneID: "America/Argentina/Salta", displayName: "" },
  { ID: 32, timeZoneID: "America/Argentina/San_Juan", displayName: "" },
  { ID: 33, timeZoneID: "America/Argentina/San_Luis", displayName: "" },
  { ID: 34, timeZoneID: "America/Argentina/Tucuman", displayName: "" },
  { ID: 35, timeZoneID: "America/Argentina/Ushuaia", displayName: "" },
  { ID: 36, timeZoneID: "America/Asuncion", displayName: "Paraguay Time" },
  { ID: 37, timeZoneID: "America/Atikokan", displayName: "" },
  { ID: 38, timeZoneID: "America/Bahia", displayName: "" },
  { ID: 39, timeZoneID: "America/Bahia_Banderas", displayName: "" },
  {
    ID: 40,
    timeZoneID: "America/Barbados",
    displayName: "Atlantic Standard Time",
  },
  { ID: 41, timeZoneID: "America/Belem", displayName: "Brazil Time" },
  {
    ID: 42,
    timeZoneID: "America/Belize",
    displayName: "Central Standard Time",
  },
  { ID: 43, timeZoneID: "America/Blanc-Sablon", displayName: "" },
  {
    ID: 44,
    timeZoneID: "America/Boa_Vista",
    displayName: "Amazon Standard Time",
  },
  { ID: 45, timeZoneID: "America/Bogota", displayName: "Colombia Time" },
  {
    ID: 46,
    timeZoneID: "America/Boise",
    displayName: "Mountain Standard Time",
  },
  {
    ID: 47,
    timeZoneID: "America/Cambridge_Bay",
    displayName: "Mountain Standard Time",
  },
  { ID: 48, timeZoneID: "America/Campo_Grande", displayName: "" },
  {
    ID: 49,
    timeZoneID: "America/Cancun",
    displayName: "Central Standard Time",
  },
  { ID: 50, timeZoneID: "America/Caracas", displayName: "Venezuela Time" },
  { ID: 51, timeZoneID: "America/Cayenne", displayName: "French Guiana Time" },
  {
    ID: 52,
    timeZoneID: "America/Chicago",
    displayName: "Central Standard Time",
  },
  {
    ID: 53,
    timeZoneID: "America/Chihuahua",
    displayName: "Mountain Standard Time",
  },
  {
    ID: 54,
    timeZoneID: "America/Costa_Rica",
    displayName: "Central Standard Time",
  },
  { ID: 55, timeZoneID: "America/Creston", displayName: "" },
  { ID: 56, timeZoneID: "America/Cuiaba", displayName: "Amazon Standard Time" },
  {
    ID: 57,
    timeZoneID: "America/Curacao",
    displayName: "Atlantic Standard Time",
  },
  {
    ID: 58,
    timeZoneID: "America/Danmarkshavn",
    displayName: "Greenwich Mean Time",
  },
  {
    ID: 59,
    timeZoneID: "America/Dawson",
    displayName: "Pacific Standard Time",
  },
  {
    ID: 60,
    timeZoneID: "America/Dawson_Creek",
    displayName: "Mountain Standard Time",
  },
  {
    ID: 61,
    timeZoneID: "America/Denver",
    displayName: "Mountain Standard Time",
  },
  {
    ID: 62,
    timeZoneID: "America/Detroit",
    displayName: "Eastern Standard Time",
  },
  {
    ID: 63,
    timeZoneID: "America/Edmonton",
    displayName: "Mountain Standard Time",
  },
  { ID: 64, timeZoneID: "America/Eirunepe", displayName: "Acre Time" },
  {
    ID: 65,
    timeZoneID: "America/El_Salvador",
    displayName: "Central Standard Time",
  },
  { ID: 66, timeZoneID: "America/Fort_Nelson", displayName: "" },
  { ID: 67, timeZoneID: "America/Fortaleza", displayName: "Brazil Time" },
  {
    ID: 68,
    timeZoneID: "America/Glace_Bay",
    displayName: "Atlantic Standard Time",
  },
  {
    ID: 69,
    timeZoneID: "America/Godthab",
    displayName: "Western Greenland Time",
  },
  {
    ID: 70,
    timeZoneID: "America/Goose_Bay",
    displayName: "Atlantic Standard Time",
  },
  {
    ID: 71,
    timeZoneID: "America/Grand_Turk",
    displayName: "Eastern Standard Time",
  },
  {
    ID: 72,
    timeZoneID: "America/Guatemala",
    displayName: "Central Standard Time",
  },
  { ID: 73, timeZoneID: "America/Guayaquil", displayName: "Ecuador Time" },
  { ID: 74, timeZoneID: "America/Guyana", displayName: "Guyana Time" },
  {
    ID: 75,
    timeZoneID: "America/Halifax",
    displayName: "Atlantic Standard Time",
  },
  {
    ID: 76,
    timeZoneID: "America/Havana",
    displayName: "Central Standard Time",
  },
  {
    ID: 77,
    timeZoneID: "America/Hermosillo",
    displayName: "Mountain Standard Time",
  },
  {
    ID: 78,
    timeZoneID: "America/Indiana/Indianapolis",
    displayName: "Eastern Standard Time",
  },
  {
    ID: 79,
    timeZoneID: "America/Indiana/Knox",
    displayName: "Eastern Standard Time",
  },
  {
    ID: 80,
    timeZoneID: "America/Indiana/Marengo",
    displayName: "Eastern Standard Time",
  },
  { ID: 81, timeZoneID: "America/Indiana/Petersburg", displayName: "" },
  { ID: 82, timeZoneID: "America/Indiana/Tell_City", displayName: "" },
  {
    ID: 83,
    timeZoneID: "America/Indiana/Vevay",
    displayName: "Eastern Standard Time",
  },
  { ID: 84, timeZoneID: "America/Indiana/Vincennes", displayName: "" },
  { ID: 85, timeZoneID: "America/Indiana/Winamac", displayName: "" },
  {
    ID: 86,
    timeZoneID: "America/Inuvik",
    displayName: "Mountain Standard Time",
  },
  {
    ID: 87,
    timeZoneID: "America/Iqaluit",
    displayName: "Eastern Standard Time",
  },
  {
    ID: 88,
    timeZoneID: "America/Jamaica",
    displayName: "Eastern Standard Time",
  },
  { ID: 89, timeZoneID: "America/Juneau", displayName: "Alaska Standard Time" },
  {
    ID: 90,
    timeZoneID: "America/Kentucky/Louisville",
    displayName: "Eastern Standard Time",
  },
  {
    ID: 91,
    timeZoneID: "America/Kentucky/Monticello",
    displayName: "Eastern Standard Time",
  },
  { ID: 92, timeZoneID: "America/La_Paz", displayName: "Bolivia Time" },
  { ID: 93, timeZoneID: "America/Lima", displayName: "Peru Time" },
  {
    ID: 94,
    timeZoneID: "America/Los_Angeles",
    displayName: "Pacific Standard Time",
  },
  { ID: 95, timeZoneID: "America/Maceio", displayName: "Brazil Time" },
  {
    ID: 96,
    timeZoneID: "America/Managua",
    displayName: "Central Standard Time",
  },
  { ID: 97, timeZoneID: "America/Manaus", displayName: "Amazon Standard Time" },
  {
    ID: 98,
    timeZoneID: "America/Martinique",
    displayName: "Atlantic Standard Time",
  },
  { ID: 99, timeZoneID: "America/Matamoros", displayName: "" },
  {
    ID: 100,
    timeZoneID: "America/Mazatlan",
    displayName: "Mountain Standard Time",
  },
  {
    ID: 101,
    timeZoneID: "America/Menominee",
    displayName: "Central Standard Time",
  },
  {
    ID: 102,
    timeZoneID: "America/Merida",
    displayName: "Central Standard Time",
  },
  { ID: 103, timeZoneID: "America/Metlakatla", displayName: "" },
  {
    ID: 104,
    timeZoneID: "America/Mexico_City",
    displayName: "Central Standard Time",
  },
  {
    ID: 105,
    timeZoneID: "America/Miquelon",
    displayName: "Pierre & Miquelon Standard Time",
  },
  { ID: 106, timeZoneID: "America/Moncton", displayName: "" },
  {
    ID: 107,
    timeZoneID: "America/Monterrey",
    displayName: "Central Standard Time",
  },
  { ID: 108, timeZoneID: "America/Montevideo", displayName: "Uruguay Time" },
  {
    ID: 109,
    timeZoneID: "America/Nassau",
    displayName: "Eastern Standard Time",
  },
  {
    ID: 110,
    timeZoneID: "America/New_York",
    displayName: "Eastern Standard Time",
  },
  {
    ID: 111,
    timeZoneID: "America/Nipigon",
    displayName: "Eastern Standard Time",
  },
  { ID: 112, timeZoneID: "America/Nome", displayName: "Alaska Standard Time" },
  {
    ID: 113,
    timeZoneID: "America/Noronha",
    displayName: "Fernando de Noronha Time",
  },
  { ID: 114, timeZoneID: "America/North_Dakota/Beulah", displayName: "" },
  {
    ID: 115,
    timeZoneID: "America/North_Dakota/Center",
    displayName: "Central Standard Time",
  },
  { ID: 116, timeZoneID: "America/North_Dakota/New_Salem", displayName: "" },
  { ID: 117, timeZoneID: "America/Ojinaga", displayName: "" },
  {
    ID: 118,
    timeZoneID: "America/Panama",
    displayName: "Eastern Standard Time",
  },
  {
    ID: 119,
    timeZoneID: "America/Pangnirtung",
    displayName: "Eastern Standard Time",
  },
  { ID: 120, timeZoneID: "America/Paramaribo", displayName: "Suriname Time" },
  {
    ID: 121,
    timeZoneID: "America/Phoenix",
    displayName: "Mountain Standard Time",
  },
  {
    ID: 122,
    timeZoneID: "America/Port_of_Spain",
    displayName: "Atlantic Standard Time",
  },
  {
    ID: 123,
    timeZoneID: "America/Port-au-Prince",
    displayName: "Eastern Standard Time",
  },
  {
    ID: 124,
    timeZoneID: "America/Porto_Velho",
    displayName: "Amazon Standard Time",
  },
  {
    ID: 125,
    timeZoneID: "America/Puerto_Rico",
    displayName: "Atlantic Standard Time",
  },
  { ID: 126, timeZoneID: "America/Punta_Arenas", displayName: "" },
  {
    ID: 127,
    timeZoneID: "America/Rainy_River",
    displayName: "Central Standard Time",
  },
  {
    ID: 128,
    timeZoneID: "America/Rankin_Inlet",
    displayName: "Central Standard Time",
  },
  { ID: 129, timeZoneID: "America/Recife", displayName: "Brazil Time" },
  {
    ID: 130,
    timeZoneID: "America/Regina",
    displayName: "Central Standard Time",
  },
  { ID: 131, timeZoneID: "America/Resolute", displayName: "" },
  { ID: 132, timeZoneID: "America/Rio_Branco", displayName: "Acre Time" },
  { ID: 133, timeZoneID: "America/Santarem", displayName: "" },
  { ID: 134, timeZoneID: "America/Santiago", displayName: "Chile Time" },
  {
    ID: 135,
    timeZoneID: "America/Santo_Domingo",
    displayName: "Atlantic Standard Time",
  },
  { ID: 136, timeZoneID: "America/Sao_Paulo", displayName: "Brazil Time" },
  {
    ID: 137,
    timeZoneID: "America/Scoresbysund",
    displayName: "Eastern Greenland Time",
  },
  { ID: 138, timeZoneID: "America/Sitka", displayName: "" },
  {
    ID: 139,
    timeZoneID: "America/St_Johns",
    displayName: "Newfoundland Standard Time",
  },
  {
    ID: 140,
    timeZoneID: "America/Swift_Current",
    displayName: "Central Standard Time",
  },
  {
    ID: 141,
    timeZoneID: "America/Tegucigalpa",
    displayName: "Central Standard Time",
  },
  {
    ID: 142,
    timeZoneID: "America/Thule",
    displayName: "Atlantic Standard Time",
  },
  {
    ID: 143,
    timeZoneID: "America/Thunder_Bay",
    displayName: "Eastern Standard Time",
  },
  { ID: 144, timeZoneID: "America/Tijuana", displayName: "" },
  { ID: 145, timeZoneID: "America/Toronto", displayName: "" },
  {
    ID: 146,
    timeZoneID: "America/Vancouver",
    displayName: "Pacific Standard Time",
  },
  {
    ID: 147,
    timeZoneID: "America/Whitehorse",
    displayName: "Pacific Standard Time",
  },
  {
    ID: 148,
    timeZoneID: "America/Winnipeg",
    displayName: "Central Standard Time",
  },
  {
    ID: 149,
    timeZoneID: "America/Yakutat",
    displayName: "Alaska Standard Time",
  },
  {
    ID: 150,
    timeZoneID: "America/Yellowknife",
    displayName: "Mountain Standard Time",
  },
  {
    ID: 151,
    timeZoneID: "Antarctica/Casey",
    displayName: "Western Standard Time (Australia)",
  },
  { ID: 152, timeZoneID: "Antarctica/Davis", displayName: "Davis Time" },
  {
    ID: 153,
    timeZoneID: "Antarctica/DumontDUrville",
    displayName: "Dumont-d'Urville Time",
  },
  { ID: 154, timeZoneID: "Antarctica/Macquarie", displayName: "" },
  { ID: 155, timeZoneID: "Antarctica/Mawson", displayName: "Mawson Time" },
  { ID: 156, timeZoneID: "Antarctica/Palmer", displayName: "Chile Time" },
  { ID: 157, timeZoneID: "Antarctica/Rothera", displayName: "Rothera Time" },
  { ID: 158, timeZoneID: "Antarctica/Syowa", displayName: "Syowa Time" },
  { ID: 159, timeZoneID: "Antarctica/Troll", displayName: "" },
  { ID: 160, timeZoneID: "Antarctica/Vostok", displayName: "Vostok Time" },
  { ID: 161, timeZoneID: "Asia/Almaty", displayName: "Alma-Ata Time" },
  { ID: 162, timeZoneID: "Asia/Amman", displayName: "Eastern European Time" },
  { ID: 163, timeZoneID: "Asia/Anadyr", displayName: "Anadyr Time" },
  { ID: 164, timeZoneID: "Asia/Aqtau", displayName: "Aqtau Time" },
  { ID: 165, timeZoneID: "Asia/Aqtobe", displayName: "Aqtobe Time" },
  { ID: 166, timeZoneID: "Asia/Ashgabat", displayName: "Turkmenistan Time" },
  { ID: 167, timeZoneID: "Asia/Atyrau", displayName: "" },
  { ID: 168, timeZoneID: "Asia/Baghdad", displayName: "Arabia Standard Time" },
  { ID: 169, timeZoneID: "Asia/Baku", displayName: "Azerbaijan Time" },
  { ID: 170, timeZoneID: "Asia/Bangkok", displayName: "Indochina Time" },
  { ID: 171, timeZoneID: "Asia/Barnaul", displayName: "" },
  { ID: 172, timeZoneID: "Asia/Beirut", displayName: "Eastern European Time" },
  { ID: 173, timeZoneID: "Asia/Bishkek", displayName: "Kirgizstan Time" },
  { ID: 174, timeZoneID: "Asia/Brunei", displayName: "Brunei Time" },
  { ID: 175, timeZoneID: "Asia/Chita", displayName: "" },
  { ID: 176, timeZoneID: "Asia/Choibalsan", displayName: "Choibalsan Time" },
  { ID: 177, timeZoneID: "Asia/Colombo", displayName: "Sri Lanka Time" },
  {
    ID: 178,
    timeZoneID: "Asia/Damascus",
    displayName: "Eastern European Time",
  },
  { ID: 179, timeZoneID: "Asia/Dhaka", displayName: "Bangladesh Time" },
  { ID: 180, timeZoneID: "Asia/Dili", displayName: "East Timor Time" },
  { ID: 181, timeZoneID: "Asia/Dubai", displayName: "Gulf Standard Time" },
  { ID: 182, timeZoneID: "Asia/Dushanbe", displayName: "Tajikistan Time" },
  { ID: 183, timeZoneID: "Asia/Famagusta", displayName: "" },
  { ID: 184, timeZoneID: "Asia/Gaza", displayName: "Eastern European Time" },
  { ID: 185, timeZoneID: "Asia/Hebron", displayName: "" },
  { ID: 186, timeZoneID: "Asia/Ho_Chi_Minh", displayName: "" },
  { ID: 187, timeZoneID: "Asia/Hong_Kong", displayName: "Hong Kong Time" },
  { ID: 188, timeZoneID: "Asia/Hovd", displayName: "Hovd Time" },
  { ID: 189, timeZoneID: "Asia/Irkutsk", displayName: "Irkutsk Time" },
  { ID: 190, timeZoneID: "Asia/Jakarta", displayName: "West Indonesia Time" },
  { ID: 191, timeZoneID: "Asia/Jayapura", displayName: "East Indonesia Time" },
  {
    ID: 192,
    timeZoneID: "Asia/Jerusalem",
    displayName: "Israel Standard Time",
  },
  { ID: 193, timeZoneID: "Asia/Kabul", displayName: "Afghanistan Time" },
  {
    ID: 194,
    timeZoneID: "Asia/Kamchatka",
    displayName: "Petropavlovsk-Kamchatski Time",
  },
  { ID: 195, timeZoneID: "Asia/Karachi", displayName: "Pakistan Time" },
  { ID: 196, timeZoneID: "Asia/Kathmandu", displayName: "" },
  { ID: 197, timeZoneID: "Asia/Khandyga", displayName: "" },
  { ID: 198, timeZoneID: "Asia/Kolkata", displayName: "" },
  { ID: 199, timeZoneID: "Asia/Krasnoyarsk", displayName: "Krasnoyarsk Time" },
  { ID: 200, timeZoneID: "Asia/Kuala_Lumpur", displayName: "Malaysia Time" },
  { ID: 201, timeZoneID: "Asia/Kuching", displayName: "Malaysia Time" },
  { ID: 202, timeZoneID: "Asia/Macau", displayName: "China Standard Time" },
  { ID: 203, timeZoneID: "Asia/Magadan", displayName: "Magadan Time" },
  {
    ID: 204,
    timeZoneID: "Asia/Makassar",
    displayName: "Central Indonesia Time",
  },
  { ID: 205, timeZoneID: "Asia/Manila", displayName: "Philippines Time" },
  { ID: 206, timeZoneID: "Asia/Nicosia", displayName: "Eastern European Time" },
  { ID: 207, timeZoneID: "Asia/Novokuznetsk", displayName: "" },
  { ID: 208, timeZoneID: "Asia/Novosibirsk", displayName: "Novosibirsk Time" },
  { ID: 209, timeZoneID: "Asia/Omsk", displayName: "Omsk Time" },
  { ID: 210, timeZoneID: "Asia/Oral", displayName: "Oral Time" },
  { ID: 211, timeZoneID: "Asia/Pontianak", displayName: "West Indonesia Time" },
  { ID: 212, timeZoneID: "Asia/Pyongyang", displayName: "Korea Standard Time" },
  { ID: 213, timeZoneID: "Asia/Qatar", displayName: "Arabia Standard Time" },
  { ID: 214, timeZoneID: "Asia/Qostanay", displayName: "" },
  { ID: 215, timeZoneID: "Asia/Qyzylorda", displayName: "Qyzylorda Time" },
  { ID: 216, timeZoneID: "Asia/Riyadh", displayName: "Arabia Standard Time" },
  { ID: 217, timeZoneID: "Asia/Sakhalin", displayName: "Sakhalin Time" },
  { ID: 218, timeZoneID: "Asia/Samarkand", displayName: "Turkmenistan Time" },
  { ID: 219, timeZoneID: "Asia/Seoul", displayName: "Korea Standard Time" },
  { ID: 220, timeZoneID: "Asia/Shanghai", displayName: "China Standard Time" },
  { ID: 221, timeZoneID: "Asia/Singapore", displayName: "Singapore Time" },
  { ID: 222, timeZoneID: "Asia/Srednekolymsk", displayName: "" },
  { ID: 223, timeZoneID: "Asia/Taipei", displayName: "China Standard Time" },
  { ID: 224, timeZoneID: "Asia/Tashkent", displayName: "Uzbekistan Time" },
  { ID: 225, timeZoneID: "Asia/Tbilisi", displayName: "Georgia Time" },
  { ID: 226, timeZoneID: "Asia/Tehran", displayName: "Iran Standard Time" },
  { ID: 227, timeZoneID: "Asia/Thimphu", displayName: "Bhutan Time" },
  { ID: 228, timeZoneID: "Asia/Tokyo", displayName: "Japan Standard Time" },
  { ID: 229, timeZoneID: "Asia/Tomsk", displayName: "" },
  { ID: 230, timeZoneID: "Asia/Ulaanbaatar", displayName: "Ulaanbaatar Time" },
  { ID: 231, timeZoneID: "Asia/Urumqi", displayName: "China Standard Time" },
  { ID: 232, timeZoneID: "Asia/Ust-Nera", displayName: "" },
  { ID: 233, timeZoneID: "Asia/Vladivostok", displayName: "Vladivostok Time" },
  { ID: 234, timeZoneID: "Asia/Yakutsk", displayName: "Yakutsk Time" },
  { ID: 235, timeZoneID: "Asia/Yangon", displayName: "" },
  {
    ID: 236,
    timeZoneID: "Asia/Yekaterinburg",
    displayName: "Yekaterinburg Time",
  },
  { ID: 237, timeZoneID: "Asia/Yerevan", displayName: "Armenia Time" },
  { ID: 238, timeZoneID: "Atlantic/Azores", displayName: "Azores Time" },
  {
    ID: 239,
    timeZoneID: "Atlantic/Bermuda",
    displayName: "Atlantic Standard Time",
  },
  {
    ID: 240,
    timeZoneID: "Atlantic/Canary",
    displayName: "Western European Time",
  },
  {
    ID: 241,
    timeZoneID: "Atlantic/Cape_Verde",
    displayName: "Cape Verde Time",
  },
  { ID: 242, timeZoneID: "Atlantic/Faroe", displayName: "" },
  {
    ID: 243,
    timeZoneID: "Atlantic/Madeira",
    displayName: "Western European Time",
  },
  {
    ID: 244,
    timeZoneID: "Atlantic/Reykjavik",
    displayName: "Greenwich Mean Time",
  },
  {
    ID: 245,
    timeZoneID: "Atlantic/South_Georgia",
    displayName: "South Georgia Standard Time",
  },
  { ID: 246, timeZoneID: "Atlantic/Stanley", displayName: "Falkland Is. Time" },
  {
    ID: 247,
    timeZoneID: "Australia/Adelaide",
    displayName: "Central Standard Time (South Australia)",
  },
  {
    ID: 248,
    timeZoneID: "Australia/Brisbane",
    displayName: "Eastern Standard Time (Queensland)",
  },
  {
    ID: 249,
    timeZoneID: "Australia/Broken_Hill",
    displayName: "Central Standard Time (South Australia/New South Wales)",
  },
  { ID: 250, timeZoneID: "Australia/Currie", displayName: "" },
  {
    ID: 251,
    timeZoneID: "Australia/Darwin",
    displayName: "Central Standard Time (Northern Territory)",
  },
  { ID: 252, timeZoneID: "Australia/Eucla", displayName: "" },
  {
    ID: 253,
    timeZoneID: "Australia/Hobart",
    displayName: "Eastern Standard Time (Tasmania)",
  },
  {
    ID: 254,
    timeZoneID: "Australia/Lindeman",
    displayName: "Eastern Standard Time (Queensland)",
  },
  {
    ID: 255,
    timeZoneID: "Australia/Lord_Howe",
    displayName: "Load Howe Standard Time",
  },
  {
    ID: 256,
    timeZoneID: "Australia/Melbourne",
    displayName: "Eastern Standard Time (Victoria)",
  },
  {
    ID: 257,
    timeZoneID: "Australia/Perth",
    displayName: "Western Standard Time (Australia)",
  },
  {
    ID: 258,
    timeZoneID: "Australia/Sydney",
    displayName: "Eastern Standard Time (New South Wales)",
  },
  {
    ID: 259,
    timeZoneID: "Europe/Amsterdam",
    displayName: "Central European Time",
  },
  {
    ID: 260,
    timeZoneID: "Europe/Andorra",
    displayName: "Central European Time",
  },
  { ID: 261, timeZoneID: "Europe/Astrakhan", displayName: "" },
  {
    ID: 262,
    timeZoneID: "Europe/Athens",
    displayName: "Eastern European Time",
  },
  {
    ID: 263,
    timeZoneID: "Europe/Belgrade",
    displayName: "Central European Time",
  },
  {
    ID: 264,
    timeZoneID: "Europe/Berlin",
    displayName: "Central European Time",
  },
  {
    ID: 265,
    timeZoneID: "Europe/Brussels",
    displayName: "Central European Time",
  },
  {
    ID: 266,
    timeZoneID: "Europe/Bucharest",
    displayName: "Eastern European Time",
  },
  {
    ID: 267,
    timeZoneID: "Europe/Budapest",
    displayName: "Central European Time",
  },
  {
    ID: 268,
    timeZoneID: "Europe/Chisinau",
    displayName: "Eastern European Time",
  },
  {
    ID: 269,
    timeZoneID: "Europe/Copenhagen",
    displayName: "Central European Time",
  },
  { ID: 270, timeZoneID: "Europe/Dublin", displayName: "Greenwich Mean Time" },
  {
    ID: 271,
    timeZoneID: "Europe/Gibraltar",
    displayName: "Central European Time",
  },
  {
    ID: 272,
    timeZoneID: "Europe/Helsinki",
    displayName: "Eastern European Time",
  },
  {
    ID: 273,
    timeZoneID: "Europe/Istanbul",
    displayName: "Eastern European Time",
  },
  {
    ID: 274,
    timeZoneID: "Europe/Kaliningrad",
    displayName: "Eastern European Time",
  },
  { ID: 275, timeZoneID: "Europe/Kiev", displayName: "Eastern European Time" },
  { ID: 276, timeZoneID: "Europe/Kirov", displayName: "" },
  {
    ID: 277,
    timeZoneID: "Europe/Lisbon",
    displayName: "Western European Time",
  },
  { ID: 278, timeZoneID: "Europe/London", displayName: "Greenwich Mean Time" },
  {
    ID: 279,
    timeZoneID: "Europe/Luxembourg",
    displayName: "Central European Time",
  },
  {
    ID: 280,
    timeZoneID: "Europe/Madrid",
    displayName: "Central European Time",
  },
  { ID: 281, timeZoneID: "Europe/Malta", displayName: "Central European Time" },
  { ID: 282, timeZoneID: "Europe/Minsk", displayName: "Eastern European Time" },
  {
    ID: 283,
    timeZoneID: "Europe/Monaco",
    displayName: "Central European Time",
  },
  { ID: 284, timeZoneID: "Europe/Moscow", displayName: "Moscow Standard Time" },
  { ID: 285, timeZoneID: "Europe/Oslo", displayName: "Central European Time" },
  { ID: 286, timeZoneID: "Europe/Paris", displayName: "Central European Time" },
  {
    ID: 287,
    timeZoneID: "Europe/Prague",
    displayName: "Central European Time",
  },
  { ID: 288, timeZoneID: "Europe/Riga", displayName: "Eastern European Time" },
  { ID: 289, timeZoneID: "Europe/Rome", displayName: "Central European Time" },
  { ID: 290, timeZoneID: "Europe/Samara", displayName: "Samara Time" },
  { ID: 291, timeZoneID: "Europe/Saratov", displayName: "" },
  {
    ID: 292,
    timeZoneID: "Europe/Simferopol",
    displayName: "Eastern European Time",
  },
  { ID: 293, timeZoneID: "Europe/Sofia", displayName: "Eastern European Time" },
  {
    ID: 294,
    timeZoneID: "Europe/Stockholm",
    displayName: "Central European Time",
  },
  {
    ID: 295,
    timeZoneID: "Europe/Tallinn",
    displayName: "Eastern European Time",
  },
  {
    ID: 296,
    timeZoneID: "Europe/Tirane",
    displayName: "Central European Time",
  },
  { ID: 297, timeZoneID: "Europe/Ulyanovsk", displayName: "" },
  {
    ID: 298,
    timeZoneID: "Europe/Uzhgorod",
    displayName: "Eastern European Time",
  },
  {
    ID: 299,
    timeZoneID: "Europe/Vienna",
    displayName: "Central European Time",
  },
  {
    ID: 300,
    timeZoneID: "Europe/Vilnius",
    displayName: "Eastern European Time",
  },
  { ID: 301, timeZoneID: "Europe/Volgograd", displayName: "" },
  {
    ID: 302,
    timeZoneID: "Europe/Warsaw",
    displayName: "Central European Time",
  },
  {
    ID: 303,
    timeZoneID: "Europe/Zaporozhye",
    displayName: "Eastern European Time",
  },
  {
    ID: 304,
    timeZoneID: "Europe/Zurich",
    displayName: "Central European Time",
  },
  {
    ID: 305,
    timeZoneID: "Indian/Chagos",
    displayName: "Indian Ocean Territory Time",
  },
  {
    ID: 306,
    timeZoneID: "Indian/Christmas",
    displayName: "Christmas Island Time",
  },
  { ID: 307, timeZoneID: "Indian/Cocos", displayName: "Cocos Islands Time" },
  {
    ID: 308,
    timeZoneID: "Indian/Kerguelen",
    displayName: "French Southern & Antarctic Lands Time",
  },
  { ID: 309, timeZoneID: "Indian/Mahe", displayName: "Seychelles Time" },
  { ID: 310, timeZoneID: "Indian/Maldives", displayName: "Maldives Time" },
  { ID: 311, timeZoneID: "Indian/Mauritius", displayName: "Mauritius Time" },
  { ID: 312, timeZoneID: "Indian/Reunion", displayName: "Reunion Time" },
  { ID: 313, timeZoneID: "Pacific/Apia", displayName: "West Samoa Time" },
  {
    ID: 314,
    timeZoneID: "Pacific/Auckland",
    displayName: "New Zealand Standard Time",
  },
  { ID: 315, timeZoneID: "Pacific/Bougainville", displayName: "" },
  {
    ID: 316,
    timeZoneID: "Pacific/Chatham",
    displayName: "Chatham Standard Time",
  },
  { ID: 317, timeZoneID: "Pacific/Chuuk", displayName: "" },
  { ID: 318, timeZoneID: "Pacific/Easter", displayName: "Easter Is. Time" },
  { ID: 319, timeZoneID: "Pacific/Efate", displayName: "Vanuatu Time" },
  { ID: 320, timeZoneID: "Pacific/Enderbury", displayName: "Phoenix Is. Time" },
  { ID: 321, timeZoneID: "Pacific/Fakaofo", displayName: "Tokelau Time" },
  { ID: 322, timeZoneID: "Pacific/Fiji", displayName: "Fiji Time" },
  { ID: 323, timeZoneID: "Pacific/Funafuti", displayName: "Tuvalu Time" },
  { ID: 324, timeZoneID: "Pacific/Galapagos", displayName: "Galapagos Time" },
  { ID: 325, timeZoneID: "Pacific/Gambier", displayName: "Gambier Time" },
  {
    ID: 326,
    timeZoneID: "Pacific/Guadalcanal",
    displayName: "Solomon Is. Time",
  },
  {
    ID: 327,
    timeZoneID: "Pacific/Guam",
    displayName: "Chamorro Standard Time",
  },
  {
    ID: 328,
    timeZoneID: "Pacific/Honolulu",
    displayName: "Hawaii Standard Time",
  },
  { ID: 329, timeZoneID: "Pacific/Kiritimati", displayName: "Line Is. Time" },
  { ID: 330, timeZoneID: "Pacific/Kosrae", displayName: "Kosrae Time" },
  {
    ID: 331,
    timeZoneID: "Pacific/Kwajalein",
    displayName: "Marshall Islands Time",
  },
  {
    ID: 332,
    timeZoneID: "Pacific/Majuro",
    displayName: "Marshall Islands Time",
  },
  { ID: 333, timeZoneID: "Pacific/Marquesas", displayName: "Marquesas Time" },
  { ID: 334, timeZoneID: "Pacific/Nauru", displayName: "Nauru Time" },
  { ID: 335, timeZoneID: "Pacific/Niue", displayName: "Niue Time" },
  { ID: 336, timeZoneID: "Pacific/Norfolk", displayName: "Norfolk Time" },
  { ID: 337, timeZoneID: "Pacific/Noumea", displayName: "New Caledonia Time" },
  {
    ID: 338,
    timeZoneID: "Pacific/Pago_Pago",
    displayName: "Samoa Standard Time",
  },
  { ID: 339, timeZoneID: "Pacific/Palau", displayName: "Palau Time" },
  {
    ID: 340,
    timeZoneID: "Pacific/Pitcairn",
    displayName: "Pitcairn Standard Time",
  },
  { ID: 341, timeZoneID: "Pacific/Pohnpei", displayName: "" },
  {
    ID: 342,
    timeZoneID: "Pacific/Port_Moresby",
    displayName: "Papua New Guinea Time",
  },
  { ID: 343, timeZoneID: "Pacific/Rarotonga", displayName: "Cook Is. Time" },
  { ID: 344, timeZoneID: "Pacific/Tahiti", displayName: "Tahiti Time" },
  { ID: 345, timeZoneID: "Pacific/Tarawa", displayName: "Gilbert Is. Time" },
  { ID: 346, timeZoneID: "Pacific/Tongatapu", displayName: "Tonga Time" },
  { ID: 347, timeZoneID: "Pacific/Wake", displayName: "Wake Time" },
  {
    ID: 348,
    timeZoneID: "Pacific/Wallis",
    displayName: "Wallis & Futuna Time",
  },
];

export const sortedTimeZones = () => {
  return timeZones.sort((a, b) => (a.displayName > b.displayName ? 1 : -1));
};

export const uniqueTimeZones = () => {
  const uniqueTimeZones = _.groupBy(timeZones, "displayName");
  const uniqueTimeZoneKeys = Object.keys(uniqueTimeZones);
  const commonUniqueTimeZonesKeys = uniqueTimeZoneKeys.filter((key) => {
    let timeZoneLength = uniqueTimeZones[key].length;
    if (timeZoneLength > 1 && uniqueTimeZones[key][0].displayName !== "") {
      return uniqueTimeZones[key][0];
    }
    return false;
  });
  let commonUniqueTimeZones = commonUniqueTimeZonesKeys.map(
    (key) => uniqueTimeZones[key][0]
  );

  commonUniqueTimeZones.sort((a, b) =>
    a.displayName > b.displayName ? 1 : -1
  );

  const currentTimeZone = timeZones.find(
    (timeZone) =>
      timeZone.timeZoneID === Intl.DateTimeFormat().resolvedOptions().timeZone
  );

  commonUniqueTimeZones.unshift(currentTimeZone);

  return commonUniqueTimeZones;
};
